export const controlStyles = {
  buttonBase: "inline-flex min-h-10 items-center justify-center gap-2 whitespace-nowrap rounded-[4px] border border-[var(--oc-hairline-strong)] bg-transparent px-4 py-1 text-center text-sm font-medium leading-[2] text-[var(--oc-ink)] no-underline transition-colors hover:border-[var(--oc-accent)] hover:bg-[var(--oc-accent-softer)] hover:text-[var(--oc-ink)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--oc-accent)] disabled:cursor-not-allowed disabled:border-[var(--oc-hairline)] disabled:bg-transparent disabled:text-[var(--oc-stone)] disabled:opacity-60 disabled:hover:border-[var(--oc-hairline)] disabled:hover:bg-transparent disabled:hover:text-[var(--oc-stone)] max-[520px]:w-full",
  buttonPrimary: "border-[var(--oc-primary)] bg-[var(--oc-primary-soft)] text-[var(--oc-ink)] hover:border-[var(--oc-primary-active)] hover:bg-[var(--oc-primary-softer)] hover:text-[var(--oc-ink)] disabled:border-[var(--oc-hairline)] disabled:bg-transparent disabled:text-[var(--oc-stone)]",
  buttonSoft: "bg-[var(--oc-surface-soft)] text-[var(--oc-ink)] hover:border-[var(--oc-accent)] hover:bg-[var(--oc-accent-softer)] disabled:bg-transparent disabled:text-[var(--oc-stone)]",
  buttonDanger: "border-[var(--oc-danger)] bg-[var(--oc-danger-soft)] text-[var(--oc-ink)] hover:border-[var(--oc-danger)] hover:bg-[var(--oc-danger)] hover:text-white disabled:border-[var(--oc-hairline)] disabled:bg-transparent disabled:text-[var(--oc-stone)]",
  input: "min-h-10 w-full rounded-[4px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] px-3 py-2 text-base font-normal leading-normal text-[var(--oc-ink)] outline-none transition-colors placeholder:text-[var(--oc-stone)] focus:border-[var(--oc-accent)] focus:bg-[var(--oc-canvas-deep)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--oc-accent)]",
  textarea: "min-h-[132px] w-full resize-y rounded-[4px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] px-3 py-2 text-base font-normal leading-normal text-[var(--oc-ink)] outline-none transition-colors placeholder:text-[var(--oc-stone)] focus:border-[var(--oc-accent)] focus:bg-[var(--oc-canvas-deep)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--oc-accent)]",
  selectWrap: "relative block oc-select-wrap",
  select: "min-h-10 w-full appearance-none rounded-[4px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] px-3 py-2 pr-12 text-base font-normal leading-normal text-[var(--oc-ink)] outline-none transition-colors focus:border-[var(--oc-accent)] focus:bg-[var(--oc-canvas-deep)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--oc-accent)]",
  filterField: "grid gap-1",
};
