export const dataDisplayStyles = {
  countCard: "grid min-w-[132px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] px-4 py-3 text-center",
  countLabel: "text-xs font-bold uppercase leading-normal text-[var(--oc-muted)]",
  countValue: "mt-1 text-[34px] font-bold leading-[1.15] text-[var(--oc-ink)]",
  metricGrid: "mt-4 grid grid-cols-3 gap-4 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1",
  metricCard: "flex min-h-[136px] flex-col gap-2 border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-6 text-[var(--oc-ink)] max-[760px]:p-4",
  metricValue: "text-[clamp(28px,4vw,40px)] font-bold leading-[1.2] text-[var(--oc-ink)]",
  miniMetric: "border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-6 text-[var(--oc-ink)] max-[760px]:p-4",
  miniValue: "text-[28px] font-bold leading-[1.2] text-[var(--oc-ink)]",
  detailMetrics: "grid grid-cols-3 gap-3 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1",
  pillMarked: "inline-flex min-h-7 w-fit items-center rounded-[4px] border border-[var(--oc-hairline-strong)] bg-transparent px-2 py-1 text-xs font-medium uppercase leading-normal text-[var(--oc-muted)] oc-x-before",
  pill: "inline-flex min-h-7 w-fit items-center rounded-[4px] border border-[var(--oc-hairline-strong)] bg-transparent px-2 py-1 text-xs font-medium uppercase leading-normal text-[var(--oc-muted)]",
  pillSelected: "border-[var(--oc-accent)] bg-[var(--oc-accent-softer)] text-[var(--oc-ink)]",
  reviewBox: "mt-4 border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] p-6 text-[var(--oc-ink)] max-[760px]:p-4",
  ratingGrid: "mt-3 grid grid-cols-4 gap-3 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1",
  reviewThoughts: "mt-3 leading-normal text-[var(--oc-body)]",
  tablePanel: "mt-4 overflow-hidden border border-[var(--oc-hairline)] bg-[var(--oc-surface)] text-[var(--oc-ink)] p-6 max-[760px]:p-4",
  tableTitle: "pb-3 text-xs font-bold uppercase leading-normal text-[var(--oc-muted)]",
  tableTitleMarked: "pb-3 text-xs font-bold uppercase leading-normal text-[var(--oc-muted)] oc-plus-before",
  tableScroll: "max-h-[460px] overflow-auto border-t border-[var(--oc-hairline)] max-[760px]:max-h-[300px]",
  table: "w-full min-w-[860px] border-collapse text-sm leading-normal text-[var(--oc-body)] [&_td]:border-b [&_td]:border-[var(--oc-hairline)] [&_td]:px-2 [&_td]:py-3 [&_td]:text-left [&_td]:align-middle [&_th]:sticky [&_th]:top-0 [&_th]:z-[1] [&_th]:border-b [&_th]:border-[var(--oc-hairline)] [&_th]:bg-[var(--oc-canvas-deep)] [&_th]:px-2 [&_th]:py-3 [&_th]:text-left [&_th]:align-middle [&_th]:text-xs [&_th]:font-bold [&_th]:uppercase [&_th]:text-[var(--oc-ink)] [&_tbody_tr:nth-child(even)]:bg-white/[0.02]",
  emptyState: "border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] p-6 text-[var(--oc-muted)] max-[760px]:p-4",
  emptyMarked: "border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] p-6 text-[var(--oc-muted)] oc-empty-before max-[760px]:p-4",
  emptyTableCell: "text-center text-[var(--oc-muted)]",
};
