export const dataDisplayStyles = {
  countCard: "grid min-w-[132px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] px-4 py-3 text-center",
  countLabel: "text-xs font-bold uppercase leading-normal text-[var(--oc-muted)]",
  countValue: "mt-1 text-[34px] font-bold leading-[1.15] text-[var(--oc-ink)]",
  metricGrid: "grid grid-cols-3 gap-4 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1 max-[760px]:gap-3",
  metricCard: "flex min-h-[136px] min-w-0 flex-col justify-between gap-3 border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-6 text-[var(--oc-ink)] max-[760px]:min-h-[120px] max-[760px]:p-4",
  metricValue: "text-[clamp(28px,4vw,40px)] font-bold leading-[1.2] text-[var(--oc-ink)]",
  metricActions: "mt-auto grid grid-cols-2 gap-2 max-[520px]:grid-cols-1",
  miniMetric: "border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-6 text-[var(--oc-ink)] max-[760px]:p-4",
  miniValue: "text-[28px] font-bold leading-[1.2] text-[var(--oc-ink)]",
  detailMetrics: "grid grid-cols-3 gap-3 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1",
  sessionDetailHeader: "grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4 border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-6 text-[var(--oc-ink)] max-[900px]:grid-cols-1 max-[760px]:p-4",
  sessionDetailTitle: "mt-1 text-[clamp(20px,2.4vw,28px)] font-bold leading-[1.25] text-[var(--oc-ink)]",
  tagPillRow: "mt-3 flex flex-wrap gap-2",
  sessionStatStrip: "grid min-w-[360px] grid-cols-3 border border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] max-[900px]:min-w-0 max-[520px]:grid-cols-1",
  sessionStatItem: "border-r border-[var(--oc-hairline)] px-3 py-2 last:border-r-0 max-[520px]:border-r-0 max-[520px]:border-b max-[520px]:last:border-b-0",
  sessionStatLabel: "block text-[11px] font-bold uppercase leading-normal text-[var(--oc-muted)]",
  sessionStatValue: "mt-1 block text-sm font-bold leading-normal text-[var(--oc-ink)]",
  pillMarked: "inline-flex min-h-7 w-fit max-w-full min-w-0 items-center gap-1.5 overflow-hidden whitespace-nowrap rounded-[4px] border border-[var(--oc-hairline-strong)] bg-transparent px-2 py-1 text-xs font-medium uppercase leading-normal text-[var(--oc-muted)] [&>span:last-child]:truncate oc-x-before",
  pill: "inline-flex min-h-7 w-fit max-w-full min-w-0 items-center gap-1.5 overflow-hidden whitespace-nowrap rounded-[4px] border border-[var(--oc-hairline-strong)] bg-transparent px-2 py-1 text-xs font-medium uppercase leading-normal text-[var(--oc-muted)] [&>span:last-child]:truncate",
  pillSelected: "border-[var(--oc-accent)] bg-[var(--oc-accent-softer)] text-[var(--oc-ink)]",
  reviewBox: "mt-4 border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] p-5 text-[var(--oc-ink)] max-[760px]:p-4",
  ratingGrid: "mt-3 grid grid-cols-4 gap-2 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1",
  reviewThoughts: "mt-3 border-t border-[var(--oc-hairline)] pt-3 leading-normal text-[var(--oc-body)]",
  ratingPill: "grid min-h-9 grid-cols-[minmax(0,1fr)_auto] items-center gap-3 rounded-[4px] border border-[var(--oc-hairline)] bg-[var(--oc-surface)] px-3 py-1.5 text-xs uppercase leading-normal text-[var(--oc-muted)]",
  ratingLabel: "truncate font-bold",
  ratingValue: "shrink-0 font-bold text-[var(--oc-ink)]",
  tablePanel: "mt-4 w-full max-w-full min-w-0 overflow-hidden border border-[var(--oc-hairline)] bg-[var(--oc-surface)] text-[var(--oc-ink)]",
  tableTitle: "px-4 py-3 text-xs font-bold uppercase leading-normal text-[var(--oc-muted)]",
  tableTitleMarked: "px-4 py-3 text-xs font-bold uppercase leading-normal text-[var(--oc-muted)] oc-plus-before",
  tableScroll: "w-full max-w-full min-w-0 max-h-[520px] touch-pan-x overflow-x-auto overflow-y-auto overscroll-contain border-t border-[var(--oc-hairline)] outline-none [scrollbar-gutter:stable] focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[var(--oc-accent)] max-[760px]:max-h-[360px]",
  table: "w-full min-w-[820px] border-separate border-spacing-0 text-sm leading-normal text-[var(--oc-body)] [&_td]:border-b [&_td]:border-r [&_td]:border-[var(--oc-hairline)] [&_td]:bg-[var(--oc-surface)] [&_td]:px-3 [&_td]:py-3 [&_td]:text-left [&_td]:align-middle [&_td:first-child]:border-l [&_th]:sticky [&_th]:top-0 [&_th]:z-[2] [&_th]:border-b [&_th]:border-r [&_th]:border-[var(--oc-hairline)] [&_th]:bg-[var(--oc-canvas-deep)] [&_th]:px-3 [&_th]:py-3 [&_th]:text-left [&_th]:align-middle [&_th]:text-[11px] [&_th]:font-bold [&_th]:uppercase [&_th]:tracking-[0.02em] [&_th]:text-[var(--oc-muted)] [&_th:first-child]:border-l [&_tbody_tr:nth-child(even)_td]:bg-white/[0.025] [&_tbody_tr:hover_td]:bg-white/[0.04]",
  tableSetCell: "w-[76px] whitespace-nowrap font-bold text-[var(--oc-ink)]",
  tableTimeCell: "whitespace-nowrap tabular-nums",
  tableActionHeader: "sticky right-0 z-[3] w-[96px] bg-[var(--oc-canvas-deep)] shadow-[-1px_0_0_var(--oc-hairline)]",
  tableActionCell: "sticky right-0 z-[1] w-[96px] bg-[var(--oc-surface)] shadow-[-1px_0_0_var(--oc-hairline)]",
  tableActionButton: "min-h-8 px-3 py-0 text-xs leading-[2]",
  emptyState: "flex min-h-[96px] items-center border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] p-6 leading-normal text-[var(--oc-muted)] max-[760px]:min-h-[82px] max-[760px]:p-4",
  emptyStateText: "min-w-0 flex-1",
  emptyStateAction: "ml-auto shrink-0 max-[520px]:ml-0 max-[520px]:w-full",
  emptyTableCell: "text-center text-[var(--oc-muted)]",
};
