export const exerciseStyles = {
  exerciseFilterGrid: "mt-4 grid grid-cols-[minmax(260px,1.4fr)_repeat(4,minmax(150px,1fr))] gap-3 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1 max-[760px]:gap-2",
  browserCard: "mt-4 min-w-0 overflow-hidden border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-0 text-[var(--oc-ink)] max-[760px]:mt-3",
  browserHeader: "flex min-w-0 items-start justify-between gap-4 border-b border-[var(--oc-hairline)] p-6 max-[1120px]:items-stretch max-[760px]:flex-col max-[760px]:items-stretch max-[760px]:gap-3 max-[760px]:p-4",
  exerciseBrowserBody: "grid h-[clamp(560px,calc(100vh-220px),760px)] min-h-0 grid-cols-[minmax(280px,0.44fr)_minmax(0,1fr)] items-stretch overflow-hidden max-[1120px]:h-auto max-[1120px]:overflow-visible max-[1120px]:grid-cols-1",
  exerciseList: "grid h-full max-h-full min-h-0 content-start self-stretch overflow-y-scroll overscroll-contain border-r border-[var(--oc-hairline)] max-[1120px]:max-h-[430px] max-[1120px]:border-r-0 max-[1120px]:border-b max-[760px]:max-h-[320px]",
  exerciseRow: "grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-0 border-b border-[var(--oc-hairline)] bg-transparent p-4 text-left text-[var(--oc-body)] transition-colors hover:bg-[var(--oc-surface-soft)] hover:text-[var(--oc-ink)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--oc-accent)] max-[760px]:gap-3 max-[760px]:p-3 [contain:layout_paint_style] [content-visibility:auto] [contain-intrinsic-size:96px]",
  exerciseDetailCard: "min-h-full min-w-0 border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-6 text-[var(--oc-ink)] max-[760px]:min-h-0 max-[760px]:p-4",
  exerciseBadgeGrid: "mt-4 grid grid-cols-4 gap-3 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-2 max-[520px]:grid-cols-1",
  infoBadge: "min-h-[100px] min-w-0 border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] p-6 text-[var(--oc-ink)] max-[760px]:min-h-[86px] max-[760px]:p-3",
  infoBadgeValue: "mt-1 text-[15px] font-bold leading-normal text-[var(--oc-ink)]",
  sectionBlock: "mt-6 border-t border-[var(--oc-hairline)] pt-4 max-[760px]:mt-4 max-[760px]:pt-3",
  pillWrap: "mt-2 flex flex-wrap gap-2",
  videoCard: "mt-6 min-w-0 border border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] p-6 text-[var(--oc-ink)] max-[760px]:mt-4 max-[760px]:p-3",
  videoFrame: "relative mt-4 aspect-video overflow-hidden border border-[var(--oc-hairline-strong)] bg-black [&_iframe]:h-full [&_iframe]:w-full [&_iframe]:border-0",
  videoPlaceholder: "grid h-full min-h-[330px] w-full place-items-center rounded-none border-0 bg-black p-6 text-center text-[var(--oc-ink)] whitespace-normal hover:border-0 hover:bg-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--oc-accent)] max-[760px]:min-h-[190px] max-[760px]:p-4",
  videoPlaceholderTitle: "mt-2 block text-[clamp(24px,3vw,34px)] font-bold leading-[1.35] text-[var(--oc-ink)] max-[760px]:text-[22px]",
  videoPlaceholderCopy: "mt-2 block max-w-[440px] text-sm leading-normal text-[var(--oc-muted)]",
  demoEmpty: "mt-4 border border-dashed border-[var(--oc-hairline-strong)] bg-[var(--oc-canvas-deep)] p-6 text-[var(--oc-body)] max-[760px]:p-4",
};
