export const exerciseStyles = {
  exerciseFilterGrid: "mt-3 grid grid-cols-[minmax(240px,1.5fr)_repeat(4,minmax(130px,1fr))] gap-2.5 max-[1120px]:grid-cols-3 max-[900px]:grid-cols-2 max-[760px]:grid-cols-1 max-[760px]:gap-2",
  exerciseSearchField: "max-[1120px]:col-span-2 max-[760px]:col-span-1",
  browserCard: "mt-4 min-w-0 overflow-hidden border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-0 text-[var(--oc-ink)] max-[760px]:mt-3",
  browserHeader: "min-w-0 border-b border-[var(--oc-hairline)]",
  browserHeaderSummary: "flex min-w-0 items-end gap-4 max-[760px]:flex-col max-[760px]:items-start max-[760px]:gap-3",
  selectedExercisePill: "mb-0.5 max-w-[min(420px,50%)] shrink min-[761px]:ml-auto [&>span:last-child]:truncate max-[760px]:max-w-full",
  exerciseBrowserBody: "grid h-[clamp(560px,calc(100vh-220px),760px)] min-h-0 grid-cols-[minmax(340px,0.55fr)_minmax(0,1fr)] items-stretch overflow-hidden max-[1120px]:h-auto max-[1120px]:overflow-visible max-[1120px]:grid-cols-1",
  exerciseList: "grid h-full max-h-full min-h-0 content-start self-stretch overflow-y-scroll overscroll-contain border-r border-[var(--oc-hairline)] max-[1120px]:max-h-[430px] max-[1120px]:border-r-0 max-[1120px]:border-b max-[760px]:max-h-[320px]",
  exerciseRow: "grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-0 border-b border-[var(--oc-hairline)] bg-transparent px-4 py-3.5 text-left text-[var(--oc-body)] transition-colors hover:bg-[var(--oc-surface-soft)] hover:text-[var(--oc-ink)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--oc-accent)] max-[760px]:p-3 [contain:layout_paint_style] [content-visibility:auto] [contain-intrinsic-size:88px]",
  exerciseDetailPane: "min-h-0 min-w-0 overflow-y-auto overscroll-contain p-6 [scrollbar-gutter:stable] max-[1120px]:overflow-visible max-[1120px]:p-6 max-[760px]:p-4",
  exerciseDetailCard: "min-w-0 text-[var(--oc-ink)]",
  exerciseBadgeGrid: "mt-4 grid grid-cols-4 gap-2 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-2 max-[520px]:grid-cols-1",
  infoBadge: "min-h-[76px] min-w-0 border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] p-3 text-[var(--oc-ink)]",
  infoBadgeValue: "mt-1 [overflow-wrap:anywhere] text-[15px] font-bold leading-normal text-[var(--oc-ink)]",
  sectionBlock: "mt-5 border-t border-[var(--oc-hairline)] pt-4 max-[760px]:mt-4 max-[760px]:pt-3",
  pillWrap: "mt-2 flex flex-wrap gap-2",
  videoCard: "mt-5 min-w-0 border border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] p-4 text-[var(--oc-ink)] max-[760px]:mt-4 max-[760px]:p-3",
  videoFrame: "relative mt-4 aspect-video overflow-hidden border border-[var(--oc-hairline-strong)] bg-black [&_iframe]:h-full [&_iframe]:w-full [&_iframe]:border-0",
  videoLoadPanel: "mt-4 min-h-[132px] overflow-hidden border border-[var(--oc-hairline-strong)] bg-black max-[760px]:min-h-[112px]",
  videoPlaceholder: "grid min-h-[132px] w-full place-items-center rounded-none border-0 bg-black p-4 text-center text-[var(--oc-ink)] whitespace-normal hover:border-0 hover:bg-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--oc-accent)] max-[760px]:min-h-[112px]",
  videoPlaceholderTitle: "mt-2 block text-xl font-bold leading-[1.35] text-[var(--oc-ink)]",
  demoEmpty: "mt-4 border border-dashed border-[var(--oc-hairline-strong)] bg-[var(--oc-canvas-deep)] p-6 text-[var(--oc-body)] max-[760px]:p-4",
};
