export const historyStyles = {
  historyCard: "relative mt-4 min-w-0 overflow-visible border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-0 text-[var(--oc-ink)] max-[760px]:mt-3",
  historyHeader: "grid grid-cols-[minmax(220px,1fr)_auto] items-start gap-4 border-b border-[var(--oc-hairline)] p-6 max-[1120px]:grid-cols-1 max-[1120px]:items-stretch max-[760px]:p-4",
  actionGroups: "flex flex-wrap items-start justify-end gap-2 max-[1120px]:justify-start max-[620px]:grid max-[620px]:grid-cols-1",
  actionGroup: "w-fit min-w-0 border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] px-2 py-1.5 text-[var(--oc-ink)] max-[620px]:w-full",
  actionGroupCompact: "w-fit min-w-0 max-[620px]:w-full",
  actionButtons: "mt-1 flex flex-wrap gap-1.5 max-[620px]:grid max-[620px]:grid-cols-2",
  historyListView: "relative grid gap-0",
  historyListToolbar: "relative z-30 flex items-center justify-between gap-4 border-b border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] px-6 py-4 max-[760px]:grid max-[760px]:grid-cols-1 max-[760px]:gap-3 max-[760px]:px-4 max-[760px]:py-3",
  historyListTools: "relative z-30 flex min-w-0 items-end justify-end gap-3 max-[760px]:justify-start max-[520px]:grid max-[520px]:grid-cols-[minmax(0,1fr)_auto]",
  historyFilterField: "w-[220px] max-[520px]:w-full",
  viewToggle: "inline-flex shrink-0 overflow-hidden rounded-[4px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)]",
  viewToggleButton: "inline-flex h-10 w-10 items-center justify-center border-0 border-r border-[var(--oc-hairline)] bg-transparent text-[var(--oc-muted)] transition-colors last:border-r-0 hover:bg-[var(--oc-surface-muted)] hover:text-[var(--oc-ink)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--oc-accent)]",
  viewToggleButtonActive: "bg-[var(--oc-primary-soft)] text-[var(--oc-ink)]",
  viewIconList: "grid h-4 w-4 content-center gap-[3px] [&_span]:block [&_span]:h-px [&_span]:w-4 [&_span]:bg-current",
  viewIconGrid: "grid h-4 w-4 grid-cols-2 gap-[3px] [&_span]:block [&_span]:h-[6px] [&_span]:w-[6px] [&_span]:border [&_span]:border-current",
  historyPagination: "flex items-center justify-end gap-1.5 border-t border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] px-4 py-2 max-[760px]:justify-between max-[760px]:gap-2 max-[760px]:px-3 max-[760px]:py-3",
  historyPageIndicator: "min-w-[84px] text-center text-[11px] font-bold uppercase leading-none text-[var(--oc-muted)] max-[760px]:min-w-0 max-[760px]:flex-1",
  historyDetailView: "grid gap-0",
  historyDetailToolbar: "flex items-center justify-between gap-3 border-b border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] px-6 py-4 max-[760px]:px-4 max-[760px]:py-3",
  sessionListPanel: "grid min-w-0 content-start",
  sessionListButton: "min-h-[88px] w-full border-0 border-b border-[var(--oc-hairline)] bg-transparent px-6 py-4 text-left text-[var(--oc-body)] transition-colors hover:bg-[var(--oc-surface-soft)] hover:text-[var(--oc-ink)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--oc-accent)] max-[760px]:min-h-[82px] max-[760px]:px-4 max-[760px]:py-3 [contain:layout_paint_style] [content-visibility:auto] [contain-intrinsic-size:88px]",
  sessionListPlaceholder: "min-h-[88px] border-0 border-b border-transparent max-[760px]:hidden",
  sessionListMeta: "mt-1 overflow-hidden text-ellipsis whitespace-nowrap text-xs uppercase leading-normal text-[var(--oc-muted)]",
  sessionCardGrid: "grid grid-cols-3 gap-3 p-4 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1 max-[760px]:gap-2 max-[760px]:p-3",
  sessionCardButton: "min-h-[150px] min-w-0 border border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] p-4 text-left text-[var(--oc-body)] transition-colors hover:border-[var(--oc-hairline-strong)] hover:bg-[var(--oc-surface-soft)] hover:text-[var(--oc-ink)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--oc-accent)] max-[760px]:min-h-[126px] max-[760px]:p-3",
  sessionCardPlaceholder: "min-h-[150px] border border-transparent max-[760px]:hidden",
  sessionCardTop: "flex min-w-0 items-start justify-between gap-3",
  sessionCardTitle: "mt-4 overflow-hidden text-ellipsis text-base font-bold leading-[1.45] text-[var(--oc-ink)] max-[760px]:mt-3",
  sessionCardMeta: "mt-2 overflow-hidden text-ellipsis whitespace-nowrap text-xs uppercase leading-normal text-[var(--oc-muted)]",
  rowTop: "flex min-w-0 items-start justify-between gap-3 max-[760px]:items-start",
  rowTitle: "mt-1 overflow-hidden text-ellipsis text-sm font-bold leading-[1.45] text-current",
  rowMeta: "mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs uppercase leading-normal text-[var(--oc-muted)]",
  rowMetaSelected: "text-[var(--oc-muted)]",
  detailPane: "min-w-0 p-6 max-[760px]:p-4",
};
