export const historyStyles = {
  historyCard: "mt-4 overflow-hidden border border-[var(--oc-hairline)] bg-[var(--oc-surface)] p-0 text-[var(--oc-ink)]",
  historyHeader: "grid grid-cols-[minmax(220px,1fr)_auto] items-start gap-4 border-b border-[var(--oc-hairline)] p-6 max-[1120px]:grid-cols-1 max-[1120px]:items-stretch max-[760px]:p-4",
  actionGroups: "flex flex-wrap items-start justify-end gap-2 max-[1120px]:justify-start",
  actionGroup: "w-fit border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] px-2 py-1.5 text-[var(--oc-ink)]",
  actionGroupCompact: "w-fit min-w-0",
  actionButtons: "mt-1 flex flex-wrap gap-1.5",
  historyListView: "grid gap-0",
  historyListToolbar: "flex items-center justify-between gap-4 border-b border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] px-6 py-4 max-[760px]:px-4",
  viewToggle: "inline-flex shrink-0 overflow-hidden rounded-[4px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)]",
  viewToggleButton: "inline-flex h-10 w-10 items-center justify-center border-0 border-r border-[var(--oc-hairline)] bg-transparent text-[var(--oc-muted)] transition-colors last:border-r-0 hover:bg-[var(--oc-surface-muted)] hover:text-[var(--oc-ink)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--oc-accent)]",
  viewToggleButtonActive: "bg-[var(--oc-primary-soft)] text-[var(--oc-ink)]",
  viewIconList: "grid h-4 w-4 content-center gap-[3px] [&_span]:block [&_span]:h-px [&_span]:w-4 [&_span]:bg-current",
  viewIconGrid: "grid h-4 w-4 grid-cols-2 gap-[3px] [&_span]:block [&_span]:h-[6px] [&_span]:w-[6px] [&_span]:border [&_span]:border-current",
  historyPagination: "flex items-center justify-end gap-2 border-t border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] px-6 py-4 max-[760px]:justify-between max-[760px]:px-4",
  historyPageIndicator: "min-w-[104px] text-center text-xs font-bold uppercase leading-normal text-[var(--oc-muted)]",
  historyDetailView: "grid gap-0",
  historyDetailToolbar: "flex items-center justify-between gap-3 border-b border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] px-6 py-4 max-[760px]:px-4",
  sessionListPanel: "grid content-start",
  sessionListButton: "w-full border-0 border-b border-[var(--oc-hairline)] bg-transparent px-6 py-4 text-left text-[var(--oc-body)] transition-colors hover:bg-[var(--oc-surface-soft)] hover:text-[var(--oc-ink)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--oc-accent)] max-[760px]:px-4 [contain:layout_paint_style] [content-visibility:auto] [contain-intrinsic-size:88px]",
  sessionListMeta: "mt-1 truncate text-xs uppercase leading-normal text-[var(--oc-muted)]",
  sessionCardGrid: "grid grid-cols-3 gap-3 p-4 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1",
  sessionCardButton: "min-h-[150px] border border-[var(--oc-hairline)] bg-[var(--oc-canvas-deep)] p-4 text-left text-[var(--oc-body)] transition-colors hover:border-[var(--oc-hairline-strong)] hover:bg-[var(--oc-surface-soft)] hover:text-[var(--oc-ink)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--oc-accent)]",
  sessionCardTop: "flex items-start justify-between gap-3",
  sessionCardTitle: "mt-4 text-base font-bold leading-[1.45] text-[var(--oc-ink)]",
  sessionCardMeta: "mt-2 truncate text-xs uppercase leading-normal text-[var(--oc-muted)]",
    rowTop: "flex items-start justify-between gap-3 max-[760px]:items-start",
  rowTitle: "mt-1 text-sm font-bold leading-[1.45] text-current",
  rowMeta: "mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs uppercase leading-normal text-[var(--oc-muted)]",
  rowMetaSelected: "text-[var(--oc-muted)]",
  detailPane: "min-w-0 p-6 max-[760px]:p-4",
};
