export const settingsStyles = {
  settingsModal: "flex h-[min(820px,calc(100vh-40px))] w-[min(760px,100%)] flex-col overflow-hidden border border-[var(--oc-hairline-strong)] bg-[var(--oc-canvas)] text-[var(--oc-ink)] motion-safe:animate-[modalIn_var(--transition-base)_both] max-[760px]:h-[100dvh] max-[760px]:w-full max-[760px]:border-0",
  settingsOverlay: "max-[760px]:p-0",
  settingsHeader: "relative border-b border-[var(--oc-hairline)] p-4 pr-16 max-[520px]:p-3 max-[520px]:pr-14",
  settingsCloseButton: "absolute right-4 top-4 h-10 !w-10 min-w-10 p-0 text-base leading-none max-[520px]:right-3 max-[520px]:top-3",
  settingsTabs: "grid grid-cols-3 border-b border-[var(--oc-hairline)]",
  settingsTabButton: "min-h-10 border-r border-[var(--oc-hairline)] px-3 py-2 text-sm font-bold uppercase tracking-[0.14em] text-[var(--oc-muted)] last:border-r-0 hover:bg-[var(--oc-surface-soft)] hover:text-[var(--oc-ink)] max-[520px]:min-h-11 max-[520px]:px-1.5 max-[520px]:text-[11px] max-[520px]:tracking-[0.06em]",
  settingsTabButtonActive: "bg-[var(--oc-primary-soft)] text-[var(--oc-ink)]",
  settingsContent: "min-h-0 flex-1 overflow-y-auto p-4 max-[520px]:p-3",
  settingsTab: "grid content-start gap-3",
  settingsSection: "border border-[var(--oc-hairline)] bg-[var(--oc-surface)]",
  settingsSectionTitle: "border-b border-[var(--oc-hairline)] px-3 py-2 text-sm font-bold uppercase tracking-[0.14em] text-[var(--oc-muted)]",
  settingsRows: "divide-y divide-[var(--oc-hairline)]",
  settingsRow: "grid grid-cols-[minmax(0,1fr)_minmax(180px,220px)] items-center gap-3 px-3 py-2 text-sm max-[620px]:grid-cols-1 max-[620px]:gap-2 max-[520px]:py-3",
  settingsRowLabel: "min-w-0 break-words leading-normal text-[var(--oc-body)]",
  settingsNumberControl: "grid grid-cols-[minmax(0,1fr)_56px] gap-2",
  settingsUnit: "grid min-h-10 place-items-center rounded-[4px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] text-xs font-bold uppercase text-[var(--oc-muted)]",
  settingsToggle: "inline-grid w-full grid-cols-2 rounded-[4px] border border-[var(--oc-hairline-strong)] bg-[var(--oc-canvas-deep)] p-1 text-xs",
  settingsToggleButton: "min-h-8 min-w-14 rounded-[4px] border border-transparent px-3 font-bold uppercase tracking-[0.12em] text-[var(--oc-muted)] transition-colors hover:text-[var(--oc-ink)] disabled:cursor-not-allowed disabled:opacity-40",
  settingsToggleButtonActive: "border-[var(--oc-hairline-strong)] bg-[var(--oc-primary-soft)] text-[var(--oc-ink)]",
  settingsActions: "flex flex-wrap justify-end gap-2 border border-[var(--oc-hairline)] bg-[var(--oc-surface)] px-3 py-2 max-[520px]:flex-col",
  settingsActionButton: "px-3 text-xs",
  settingsStatus: "border border-[var(--oc-hairline)] bg-[var(--oc-surface)] px-3 py-2 text-sm leading-normal text-[var(--oc-body)]",
  settingsShortcutRow: "grid grid-cols-[minmax(0,1fr)_minmax(112px,auto)_auto] items-center gap-3 px-3 py-2 text-sm max-[620px]:grid-cols-[minmax(0,1fr)_auto] max-[620px]:gap-2 max-[520px]:py-3",
  settingsShortcutLabel: "min-w-0 break-words leading-normal text-[var(--oc-body)] max-[620px]:col-span-2",
  settingsShortcutKeys: "inline-flex min-h-8 min-w-[112px] max-w-[220px] items-center justify-center overflow-hidden text-ellipsis whitespace-nowrap rounded-[4px] border border-[var(--oc-hairline-strong)] bg-[var(--oc-surface-soft)] px-2 text-xs font-bold text-[var(--oc-ink)] max-[620px]:min-w-0 max-[620px]:justify-start",
  settingsShortcutActions: "flex justify-end gap-2 max-[520px]:grid max-[520px]:grid-cols-2",
};
