import { ui as sharedUi } from "@shared/styles";

export const timerStyles = {
  gridTop: "grid grid-cols-[minmax(0,1.7fr)_minmax(320px,0.95fr)] items-stretch gap-4 max-[1120px]:grid-cols-1",
  timerLayoutGrid: "grid grid-cols-3 items-stretch gap-4 max-[1120px]:grid-cols-1 max-[760px]:gap-3",
  timerHeroArea: "col-span-2 max-[1120px]:col-span-1",
  timerRestArea: "col-span-1",
  timerMetricsArea: "col-span-full",
  timerHeroHeader: "flex items-start justify-between gap-4 max-[760px]:flex-col",
  timerStatusBadge: "inline-flex min-h-8 shrink-0 items-center rounded-[4px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] px-3 text-xs font-bold uppercase leading-none text-[var(--oc-muted)]",
  timerStatusBadgeRunning: "border-[var(--oc-success)] bg-[var(--oc-success-soft)] text-[var(--oc-ink)]",
  timerSummaryMarked: "mt-4 border-t border-[var(--oc-hairline)] pt-3 text-xs font-bold uppercase leading-normal text-[var(--oc-muted)] oc-status-before",
  timerSummary: "mt-4 border-t border-[var(--oc-hairline)] pt-3 text-xs font-bold uppercase leading-normal text-[var(--oc-muted)]",
  timerPanel: "min-w-0 overflow-hidden border border-[var(--oc-hairline-strong)] bg-[var(--oc-canvas-deep)] p-6 text-[var(--oc-ink)] max-[760px]:p-4",
  bigTime: "mt-6 max-w-full overflow-hidden whitespace-nowrap text-[clamp(48px,8.8vw,96px)] font-bold leading-none text-[var(--oc-ink)] max-[760px]:mt-4 max-[760px]:text-[clamp(38px,14vw,64px)]",
  pulseDot: "mt-1.5 h-2.5 w-2.5 flex-none rounded-[4px] bg-[var(--oc-stone)]",
  pulseDotRunning: "bg-[var(--oc-success)] motion-safe:animate-[pulseDot_1200ms_ease-in-out_infinite]",
  restCard: "flex min-w-0 flex-col gap-4 max-[760px]:gap-3",
  restDisplay: "min-w-0 border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] p-4 text-[var(--oc-ink)] max-[760px]:p-3",
  restDisplayActive: "border-[var(--oc-success)] bg-[var(--oc-success-soft)]",
  restAdjustments: "mt-3 grid grid-cols-2 gap-2",
  restAdjustmentButton: "inline-flex min-h-10 items-center justify-center rounded-[4px] border border-[var(--oc-hairline-strong)] bg-[var(--oc-canvas-deep)] px-3 py-1 text-xs font-bold uppercase leading-normal text-[var(--oc-ink)] transition-colors hover:border-[var(--oc-accent)] hover:bg-[var(--oc-accent-softer)] disabled:cursor-not-allowed disabled:opacity-45",
  restTime: "mt-1 max-w-full overflow-hidden text-[clamp(36px,5vw,54px)] font-bold leading-[1.15] text-[var(--oc-ink)] max-[760px]:text-[clamp(34px,13vw,52px)]",
  restStatus: "text-right text-xs font-bold uppercase leading-normal text-[var(--oc-muted)] max-[760px]:text-left",
  restStatusActive: "text-[var(--oc-ink)]",
  progressShell: "mt-4 h-3.5 overflow-hidden rounded-[4px] border border-[var(--oc-hairline-strong)] bg-[var(--oc-canvas-deep)]",
  progressFill: "h-full bg-[var(--oc-primary)] transition-[width] duration-200 ease-linear",
  inputRow: "mt-1 grid grid-cols-[minmax(0,1fr)_72px] gap-2 max-[760px]:grid-cols-[minmax(0,1fr)_64px]",
  unitBox: "grid min-h-10 min-w-[72px] place-items-center rounded-[4px] border border-[var(--oc-hairline)] bg-[var(--oc-surface-soft)] text-xs font-bold uppercase text-[var(--oc-muted)]",
  restPresetSummary: "mt-2 text-xs font-bold uppercase leading-normal text-[var(--oc-muted)]",
  presets: "mt-2 grid grid-cols-4 gap-2 max-[760px]:grid-cols-2",
  preset: "inline-flex min-h-10 items-center justify-center gap-2 whitespace-nowrap rounded-[4px] border border-[var(--oc-hairline-strong)] bg-transparent px-4 py-1 text-center text-sm font-medium leading-[2] text-[var(--oc-ink)] transition-colors hover:border-[var(--oc-accent)] hover:bg-[var(--oc-accent-softer)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--oc-focus)] max-[520px]:w-full",
  presetActive: "border-[var(--oc-primary)] bg-[var(--oc-primary-soft)] text-[var(--oc-ink)] hover:border-[var(--oc-primary-active)] hover:bg-[var(--oc-primary-softer)] hover:text-[var(--oc-ink)]",
  buttonRow: "mt-4 grid grid-cols-2 gap-2 max-[760px]:grid-cols-1",
  timerActionGrid: "mt-4 grid grid-cols-3 gap-2 max-[1120px]:grid-cols-2 max-[760px]:grid-cols-1",
  buttonGrid: "grid grid-cols-1 gap-2",
  twoCol: "grid grid-cols-2 gap-2 max-[760px]:grid-cols-1",
  restAlert: "fixed left-1/2 top-[76px] z-[90] max-h-[calc(100dvh-100px)] w-[min(460px,calc(100%_-_32px))] -translate-x-1/2 overflow-y-auto [overflow-wrap:anywhere] border border-[var(--oc-warning)] bg-[var(--oc-canvas-deep)] p-4 text-[var(--oc-ink)] motion-safe:animate-[restAlertIn_var(--transition-base)_both] max-[760px]:top-3 max-[760px]:max-h-[calc(100dvh-108px-env(safe-area-inset-bottom))] max-[760px]:w-[calc(100%_-_24px)] max-[760px]:p-3",
  restAlertTitle: "mt-2 text-[clamp(22px,2.4vw,30px)] font-bold leading-[1.35] tracking-normal text-[var(--oc-ink)] oc-alert-before",
};

export const timerUi = {
  ...sharedUi,
  ...timerStyles,
};
